### ISSUE TITLE
При попытке получения участников сервера из таблицы хука GuildCreate, возвращает только бота

### ISSUE THREAD

**Issue by notsokodya** [devonium/gmDiscordAPI#2]
![image](https://user-images.githubusercontent.com/66978308/122242308-e1fbf180-cecb-11eb-9742-f4ea6133ddc4.png)
![image](https://user-images.githubusercontent.com/66978308/122242396-f6d88500-cecb-11eb-8537-9df61995fda7.png)

Я так и не понял почему так ¯\_(ツ)_/¯

**Comment by devonium** [comment]
Какое количество участников у вас в гильдии?

**Comment by devonium** [comment]
Перекачайте библиотеку и попробуй снова это должно помочь

**Comment by notsokodya** [comment]
![image](https://user-images.githubusercontent.com/66978308/122305255-42605280-cf0f-11eb-8fbb-9de2f13bd1fb.png)
![image](https://user-images.githubusercontent.com/66978308/122305197-2957a180-cf0f-11eb-8d3e-5fbf32aa4af7.png)
странно но теперь хук не запускается

**Comment by devonium** [comment]
Сколько у вас участников в гильдии?

**Comment by devonium** [comment]
Добавьте меня в дискорде devonium#1830

**Comment by notsokodya** [comment]
а что дальше делать?
